### Import numpy

In [1]:
import numpy as np

### Make an array with numpy

In [2]:
myarray = np.array([21,34,22,49])
myarray

array([21, 34, 22, 49])

### Sort array elements

In [3]:
sorted_myarray = np.sort(myarray)
sorted_myarray

array([21, 22, 34, 49])

### Check sorted_myarray's dimension

In [4]:
np.ndim(sorted_myarray)

1

### Shape of the sorted_myarray

In [5]:
sorted_myarray.shape

(4,)

### Find the data type of the elements in an array

In [6]:
sorted_myarray.dtype

dtype('int32')

### Size in bytes of each element in an array

In [7]:
sorted_myarray.itemsize

4

### The buffer containing the actual elements of the array

In [8]:
sorted_myarray.data

### Know the type of an object

In [9]:
type(sorted_myarray)

numpy.ndarray

### Create an uninitialized array

In [10]:
un_initialized_array = np.empty((2,3))
un_initialized_array

array([[0., 0., 0.],
       [0., 0., 0.]])

### Zeros Array

In [11]:
zeros_array = np.zeros((2,3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.]])

### Ones Array

In [12]:
ones_array = np.ones((2,3))
ones_array

array([[1., 1., 1.],
       [1., 1., 1.]])

### Create array of sequence of numbers

In [13]:
sequence_array = np.arange(0,20,2)
sequence_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Numbers between numbers

In [14]:
list_12_numbers_between_2_10 = np.linspace(2,10,12)
list_12_numbers_between_2_10

array([ 2.        ,  2.72727273,  3.45454545,  4.18181818,  4.90909091,
        5.63636364,  6.36363636,  7.09090909,  7.81818182,  8.54545455,
        9.27272727, 10.        ])

### print array

In [15]:
print(list_12_numbers_between_2_10)

[ 2.          2.72727273  3.45454545  4.18181818  4.90909091  5.63636364
  6.36363636  7.09090909  7.81818182  8.54545455  9.27272727 10.        ]


### Reshape array 

In [16]:
a = np.linspace(0,132,12)
print(a)
a = a.reshape(2,6)
print(a)
a = a.reshape(4,3)
print(a)

[  0.  12.  24.  36.  48.  60.  72.  84.  96. 108. 120. 132.]
[[  0.  12.  24.  36.  48.  60.]
 [ 72.  84.  96. 108. 120. 132.]]
[[  0.  12.  24.]
 [ 36.  48.  60.]
 [ 72.  84.  96.]
 [108. 120. 132.]]


### Generate random numbers array

In [17]:
r = np.random.rand(2,3)
r

array([[0.9621091 , 0.66320119, 0.80960213],
       [0.72215321, 0.72702855, 0.93154923]])

### Get max value in an array

In [18]:
r.max()

0.9621091046270878

### Get min value in an array

In [19]:
r.min()

0.6632011942692503

### Sum array elements

In [20]:
r.sum()

4.8156434194795406

### Sum columns in 2D Array

In [21]:
two_d_array = np.arange(12).reshape(3,4)
print(two_d_array)
two_d_array.sum(axis=0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([12, 15, 18, 21])

### Sum rows in 2D Array

In [22]:
two_d_array = np.arange(12).reshape(3,4)
print(two_d_array)
two_d_array.sum(axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 6, 22, 38])

### Get element at particular index

In [23]:
a = np.arange(6)**2
print(a)
print(a[2])

[ 0  1  4  9 16 25]
4
